// This file was generated by Mendix Business Modeler 4.0.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package unittesting.actions;

import unittesting.TestManager;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * 
 */
public class ThrowAssertionFailed extends UserAction<Boolean>
{
	private String message;

	public ThrowAssertionFailed(String message)
	{
		super();
		this.message = message;
	}

	@Override
	public Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		throw new TestManager.AssertionException(message);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public String toString()
	{
		return "ThrowAssertionFailed";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
