// This file was generated by Mendix Business Modeler 4.0.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package system.actions;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.UserAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * 
 */
public class ResetLicenseJava extends UserAction<Boolean>
{
	private IMendixObject __licenseInformation;
	private system.proxies.LicenseInformation licenseInformation;

	public ResetLicenseJava(IMendixObject licenseInformation)
	{
		super();
		this.__licenseInformation = licenseInformation;
	}

	@Override
	public Boolean executeAction() throws Exception
	{
		this.licenseInformation = __licenseInformation == null ? null : system.proxies.LicenseInformation.initialize(getContext(), __licenseInformation);

		// BEGIN USER CODE
		Core.resetLicense(licenseInformation.getMendixObject());
		addRefreshObjectFeedback(licenseInformation.getMendixObject().getId());
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public String toString()
	{
		return "ResetLicenseJava";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
