// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package communitycommons.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import communitycommons.ORM;

/**
 * Copies all common primitive attributes from source to target, which are not necessarily of the same type. This is useful to, for example, translate database object into view objects.
 * 
 * Note that no automatic type conversion is done. 
 */
public class copyAttributes extends CustomJavaAction<Boolean>
{
	private IMendixObject source;
	private IMendixObject target;

	public copyAttributes(IContext context, IMendixObject source, IMendixObject target)
	{
		super(context);
		this.source = source;
		this.target = target;
	}

	@Override
	public Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		ORM.copyAttributes(getContext(), source, target);
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public String toString()
	{
		return "copyAttributes";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
