// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package communitycommons.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import communitycommons.Logging;

/**
 * 
 */
public class CreateLogNode extends CustomJavaAction<Boolean>
{
	private String LogNode;

	public CreateLogNode(IContext context, String LogNode)
	{
		super(context);
		this.LogNode = LogNode;
	}

	@Override
	public Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		Logging.createLogNode(LogNode);
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public String toString()
	{
		return "CreateLogNode";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
