// This file was generated by Mendix Business Modeler 4.0.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package communitycommons.actions;

import com.mendix.systemwideinterfaces.core.UserAction;
import communitycommons.StringUtils;

/**
 * Applies AES encryption to the value string using a symmetric key. 
 * The keylength should exactly be 16 characters (128 bit).
 */
public class DecryptString extends UserAction<String>
{
	private String valueToDecrypt;
	private String key;

	public DecryptString(String valueToDecrypt, String key)
	{
		super();
		this.valueToDecrypt = valueToDecrypt;
		this.key = key;
	}

	@Override
	public String executeAction() throws Exception
	{
		// BEGIN USER CODE
		return StringUtils.decryptString(key, valueToDecrypt);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public String toString()
	{
		return "DecryptString";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
