// This file was generated by Mendix Business Modeler 4.0.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package communitycommons.actions;

import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;
import communitycommons.ORM;

/**
 * Returns the user that created an object 
 * 
 * (or empty if not applicable).
 */
public class getCreatedByUser extends UserAction<IMendixObject>
{
	private IMendixObject thing;

	public getCreatedByUser(IMendixObject thing)
	{
		super();
		this.thing = thing;
	}

	@Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		return ORM.getCreatedByUser(getContext(), thing);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public String toString()
	{
		return "getCreatedByUser";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
