// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package communitycommons.actions;

import system.proxies.Language;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import communitycommons.Misc;

/**
 * Get default language
 */
public class GetDefaultLanguage extends CustomJavaAction<IMendixObject>
{
	public GetDefaultLanguage(IContext context)
	{
		super(context);
	}

	@Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		Language defaultLanguage = Misc.getDefaultLanguage(getContext());
		return defaultLanguage.getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public String toString()
	{
		return "GetDefaultLanguage";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
