// This file was generated by Mendix Business Modeler 4.0.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package communitycommons.actions;

import com.mendix.systemwideinterfaces.core.UserAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import communitycommons.ORM;

/**
 * returns the Global Unique Identifier (GUID, or id) of an object.
 */
public class getGUID extends UserAction<Long>
{
	private IMendixObject item;

	public getGUID(IMendixObject item)
	{
		super();
		this.item = item;
	}

	@Override
	public Long executeAction() throws Exception
	{
		// BEGIN USER CODE
		return ORM.getGUID(item);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public String toString()
	{
		return "getGUID";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
