// This file was generated by Mendix Business Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package communitycommons.actions;

import com.mendix.systemwideinterfaces.core.IMendixObject;
import communitycommons.ORM;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

/**
 * Returns the user.name of the lock owner, or empty if the item is not locked.
 */
public class getLockOwner extends CustomJavaAction<String>
{
	private IMendixObject item;

	public getLockOwner(IContext context, IMendixObject item)
	{
		super(context);
		this.item = item;
	}

	@Override
	public String executeAction() throws Exception
	{
		// BEGIN USER CODE
		return ORM.getLockOwner(item);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public String toString()
	{
		return "getLockOwner";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
