// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package communitycommons.actions;

import communitycommons.StringUtils;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

/**
 * Hashes a value using the SHA-256 hash algorithm. 
 * 
 * - value : the value to hash
 * - length : the desired length of the hash. 
 * 
 * Returns a SHA-256 hash of 'value', with length 'length'
 */
public class Hash extends CustomJavaAction<String>
{
	private String value;
	private Long length;

	public Hash(IContext context, String value, Long length)
	{
		super(context);
		this.value = value;
		this.length = length;
	}

	@Override
	public String executeAction() throws Exception
	{
		// BEGIN USER CODE
		return StringUtils.hash(value, length.intValue());
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public String toString()
	{
		return "Hash";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
