// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package communitycommons.actions;

import communitycommons.Logging;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

/**
 * Prints a message to the Mendix log. 
 * - Lognode: the lognode to print to
 * - Loglevel: the loglevel to use (such as Info, Warning, Error etc)
 * - Message: the message to print.
 * 
 * DEPRECATED: From Mendix 2.5.3, you can use the Microflow Log activity as well.
 */
public class Log extends CustomJavaAction<Boolean>
{
	private String lognode;
	private communitycommons.proxies.LogLevel loglevel;
	private String message;

	public Log(IContext context, String lognode, String loglevel, String message)
	{
		super(context);
		this.lognode = lognode;
		this.loglevel = loglevel == null ? null : communitycommons.proxies.LogLevel.valueOf(loglevel);
		this.message = message;
	}

	@Override
	public Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		Logging.log(lognode, loglevel, message);
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public String toString()
	{
		return "Log";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
