// This file was generated by Mendix Business Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package communitycommons.actions;

import communitycommons.Misc;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

/**
 * 
 */
public class recommitInBatches extends CustomJavaAction<Boolean>
{
	private String xpath;
	private Long batchsize;
	private Boolean waitUntilFinished;
	private Boolean ascending;

	public recommitInBatches(IContext context, String xpath, Long batchsize, Boolean waitUntilFinished, Boolean ascending)
	{
		super(context);
		this.xpath = xpath;
		this.batchsize = batchsize;
		this.waitUntilFinished = waitUntilFinished;
		this.ascending = ascending;
	}

	@Override
	public Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		return Misc.recommitInBatches(xpath, batchsize.intValue(), waitUntilFinished.booleanValue(), ascending);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public String toString()
	{
		return "recommitInBatches";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
