// This file was generated by Mendix Business Modeler 4.0.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package communitycommons.actions;

import com.mendix.systemwideinterfaces.core.UserAction;
import communitycommons.ORM;

/**
 * Refreshes a certain domain object type in the client. Useful to enforce a datagrid to refresh for example.
 * 
 * -objectType : Type of the domain objects to refresh, such as System.User or MyModule.MyFirstEntity.
 *  (you can use getTypeAsString to determine this dynamically, so that the invoke of this action is not be sensitive to domain model changes).
 */
public class refreshClass extends UserAction<Boolean>
{
	private String objectType;

	public refreshClass(String objectType)
	{
		super();
		this.objectType = objectType;
	}

	@Override
	public Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		ORM.refreshClass(this, objectType);
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public String toString()
	{
		return "refreshClass";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
