// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package communitycommons.actions;

import communitycommons.ORM;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

/**
 * Removes old locks
 */
public class releaseAllInactiveLocks extends CustomJavaAction<Boolean>
{
	public releaseAllInactiveLocks(IContext context)
	{
		super(context);
	}

	@Override
	public Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		ORM.releaseOldLocks();
		return false; 
		//MWE: Lets return false :). We check this in the MF. If it returns true, than apparently a default generated java action was used and thus the code is missing.
		//Since that is bug-report reason nr. 1, we now try to avoid this situation be displaying a clear log message 
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public String toString()
	{
		return "releaseAllInactiveLocks";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
