package restservices.publish;

import java.io.IOException;

import org.eclipse.jetty.server.Authentication;
import org.eclipse.jetty.server.Request;
import org.eclipse.jetty.server.Response;

import restservices.RestServices;
import restservices.util.DataWriter;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.ISession;
import com.mendix.systemwideinterfaces.core.IUser;

public class RestServiceRequest {
	public static enum ContentType { JSON, XML, HTML }

	Request request;
	Response response;
	private ContentType contentType = ContentType.JSON;
	private IContext context;
	protected DataWriter datawriter;
	private boolean autoLogout;
	private ISession activeSession;

	public RestServiceRequest(Request request, Response response, ISession existingSession) {
		this.request = request;
		this.response = response;
		
		this.contentType = determineContentType(request);
		setResponseContentType(response, contentType);

		try {
			this.datawriter = new DataWriter(response.getOutputStream(), contentType == ContentType.HTML ? DataWriter.HTML : contentType == ContentType.XML ? DataWriter.XML : DataWriter.JSON);
		} catch (IOException e) {
			throw new RuntimeException(e);
		}

		if (!this.setupContext(existingSession)) {
			this.setStatus(401);
			this.write("Invalid credentials");
		}
		
	}

	private boolean setupContext(ISession existingSession) {
		String username = null;
		String password = null;
		ISession session = null;
		
		if (Request.BASIC_AUTH.equals(request.getAuthType())) {
			Authentication auth = request.getAuthentication();
			asdf
		}
		
		try {
			//Check credentials provided by request
			if (username != null) {
				session = Core.login(username, password);
				if (session == null)
					return false;
				
				//same user as the one in the current session? recylcle the session
				if (existingSession != null && !session.getId().equals(existingSession.getId()) && !existingSession.getUser().getName().equals(session.getUser().getName())) {
					Core.logout(session);
					session = existingSession;
				}
				else
					this.autoLogout = true;
				
			}
			
			//check session from cookies
			else if (existingSession != null)
				session = existingSession;
				
			//session found?
			if (session != null) {
				this.context = session.createContext().getSudoContext();
				this.activeSession = session;
			}
			
			return true;
		}
		catch(Exception e) {
			RestServices.LOG.warn("Failed to authenticate '" + username + "'" + e.getMessage(), e);
			return false;
		}
		
	}

	public static ContentType determineContentType(Request request) {
		if (request.getParameter(RestServices.CONTENTTYPE_PARAM) != null)
			return ContentType.valueOf(request.getParameter(RestServices.CONTENTTYPE_PARAM).toUpperCase());
		String ct = request.getHeader(RestServices.ACCEPT_HEADER);
		if (ct != null) {
			if (ct.contains("text/json"))
				return ContentType.JSON;
			if (ct.contains("html"))
				return ContentType.HTML;
			if (ct.contains("xml")) 
				return ContentType.XML;
		}
		return ContentType.JSON; //by default
	}
	
	public static void setResponseContentType(Response response, ContentType contentType) {
		response.setContentType("text/" + contentType.toString().toLowerCase()+ "; charset=UTF-8");
	}
	
	public ContentType getContentType() {
		return this.contentType;
	}
	
	public RestServiceRequest write(String data) {
		try {
			this.response.getOutputStream().write(data.getBytes(RestServices.UTF8));
		} catch (Exception e) {
			throw new RuntimeException(e);
		}
		return this;
	}

	public IContext getContext() {
		return this.context;
	}

	public void close() {
		try {
			this.response.getOutputStream().close();
		} catch (IOException e) {
			throw new RuntimeException(e);
		}
	}

	public void startHTMLDoc() {
		this.write("<!DOCTYPE HTML><html><head><style>" + RestServices.STYLESHEET + "</style><head><body>");		
	}


	public void endHTMLDoc() {
		this.write("<p><center><small>View as: <a href='?contenttype=xml'>XML</a> <a href='?contenttype=json'>JSON</a></small></center></p>");
		this.write("<hr /><p><center><small>Generated by the Mendix RestServices module</small></center></body></html>");
	}

	public void startXMLDoc() {
		this.write("<?xml version=\"1.0\" encoding=\"utf-8\"?>");
	}

	public void setStatus(int status) {
		response.setStatus(status);
	}

	public String getETag() {
		return request.getHeader(RestServices.IFNONEMATCH_HEADER);
	}

	public void dispose() {
		if (autoLogout)
			Core.logout(this.activeSession);		
	}
	
	public boolean hasUser() {
		return this.activeSession != null;
	}
	
	public IUser getCurrentUser() {
		return activeSession.getUser();
	}

	public boolean hasRole(String role) {
		if ("*".equals(role)) //TODO: make constant
			return true;
		if (!hasUser())
			return false;
		if (getCurrentUser().getUserRoleNames().contains(role))
			return true;
		return false;
	}
}
