// This file was generated by Mendix Business Modeler 4.0.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package restservices.actions;

import restservices.Utils;

import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Copies all common primitive attributes from source to target. 
 * 
 * Note that no automatic type conversion is done. 
 */
public class copyAttributes extends UserAction<Boolean>
{
	private IMendixObject source;
	private IMendixObject target;

	public copyAttributes(IMendixObject source, IMendixObject target)
	{
		super();
		this.source = source;
		this.target = target;
	}

	@Override
	public Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		Utils.copyAttributes(getContext(), source, target);
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public String toString()
	{
		return "copyAttributes";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
