// This file was generated by Mendix Business Modeler 4.0.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package restservices.actions;

import restservices.consume.RestConsumer;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * 
 */
public class delete extends UserAction<String>
{
	private String resourceUrl;
	private String optEtag;

	public delete(String resourceUrl, String optEtag)
	{
		super();
		this.resourceUrl = resourceUrl;
		this.optEtag = optEtag;
	}

	@Override
	public String executeAction() throws Exception
	{
		// BEGIN USER CODE
		return RestConsumer.deleteObject(resourceUrl, optEtag).toString();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public String toString()
	{
		return "delete";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
