// This file was generated by Mendix Business Modeler 4.0.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package restservices.actions;

import restservices.RestServices;
import com.mendix.systemwideinterfaces.core.UserAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * 
 */
public class get extends UserAction<String>
{
	private IMendixObject __stub;
	private restservices.proxies.RestObject stub;

	public get(IMendixObject stub)
	{
		super();
		this.__stub = stub;
	}

	@Override
	public String executeAction() throws Exception
	{
		this.stub = __stub == null ? null : restservices.proxies.RestObject.initialize(getContext(), __stub);

		// BEGIN USER CODE
		return RestServices.getObject(getContext(), __stub).toString();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public String toString()
	{
		return "get";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
