// This file was generated by Mendix Business Modeler 4.0.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package restservices.actions;

import restservices.RestServices;
import restservices.proxies.ServiceDefinition;
import restservices.publish.PublishedService;
import com.mendix.systemwideinterfaces.core.UserAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * 
 */
public class GetNrOfIncomingConnections extends UserAction<Long>
{
	private IMendixObject __index;
	private restservices.proxies.ServiceObjectIndex index;

	public GetNrOfIncomingConnections(IMendixObject index)
	{
		super();
		this.__index = index;
	}

	@Override
	public Long executeAction() throws Exception
	{
		this.index = __index == null ? null : restservices.proxies.ServiceObjectIndex.initialize(getContext(), __index);

		// BEGIN USER CODE
		ServiceDefinition def = index.getServiceObjectIndex_ServiceDefinition();
		if (def == null)
			return 0L;
		PublishedService service = RestServices.getService(def.getName());
		if (service == null)
			return 0L;
		return service.getChangeManager().getNrOfConnections();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public String toString()
	{
		return "GetNrOfIncomingConnections";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
