// This file was generated by Mendix Business Modeler 4.0.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package restservices.actions;

import restservices.publish.RestServiceRequest;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import communitycommons.XPath;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * 
 */
public class getRequestCookies extends UserAction<java.util.List<IMendixObject>>
{
	public getRequestCookies()
	{
		super();
	}

	@Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE
		return XPath.proxyListToMendixObjectList(RestServiceRequest.getRequestCookies(getContext()));
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public String toString()
	{
		return "getRequestCookies";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
