// This file was generated by Mendix Business Modeler 4.0.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package restservices.actions;

import restservices.proxies.FollowChangesState;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.UserAction;
import communitycommons.XPath;

/**
 * 
 */
public class resetChangeTracking extends UserAction<Boolean>
{
	private String collectionUrl;

	public resetChangeTracking(String collectionUrl)
	{
		super();
		this.collectionUrl = collectionUrl;
	}

	@Override
	public Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		XPath.create(Core.createSystemContext(), FollowChangesState.class).eq(FollowChangesState.MemberNames.CollectionUrl, collectionUrl).deleteAll();
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public String toString()
	{
		return "resetChangeTracking";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
