// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package restservices.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import restservices.consume.RestConsumer;

/**
 * 
 */
public class setGlobalRequestSettings extends CustomJavaAction<Boolean>
{
	private Long maxConcurrentRequests;
	private Long timeout;

	public setGlobalRequestSettings(IContext context, Long maxConcurrentRequests, Long timeout)
	{
		super(context);
		this.maxConcurrentRequests = maxConcurrentRequests;
		this.timeout = timeout;
	}

	@Override
	public Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		RestConsumer.setGlobalRequestSettings(maxConcurrentRequests, timeout);
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public String toString()
	{
		return "setGlobalRequestSettings";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
