// This file was generated by Mendix Business Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package restservices.actions;

import restservices.publish.MicroflowService;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

/**
 * 
 */
public class StartMicroflowServiceJava extends CustomJavaAction<Boolean>
{
	private String microflowName;
	private String securityRoleOrMicroflow;
	private String description;

	public StartMicroflowServiceJava(IContext context, String microflowName, String securityRoleOrMicroflow, String description)
	{
		super(context);
		this.microflowName = microflowName;
		this.securityRoleOrMicroflow = securityRoleOrMicroflow;
		this.description = description;
	}

	@Override
	public Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		new MicroflowService(microflowName, securityRoleOrMicroflow, description); 
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public String toString()
	{
		return "StartMicroflowServiceJava";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
